#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: yes
  vars_files: [ personal_vars/bschlueter.yml ]
  roles:
    - hub
    - user-dotfiles
    - vim-plug
    - zsh-prezto
  tasks:
    - name: Install my bin repo
      git:
        dest=~/bin
        repo=https://github.com/schlueter/bin.git
        version=master
      ignore_errors: yes
